version: "3.8"

services:
  testbackendservice:
    container_name: SerwisContainer
    build:
      context: .
      dockerfile: TestBackendService/Dockerfile
    image: testbackendservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DISABLE_HTTPS_REDIRECT=1
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"

