version: "3.8"

services:
  testbackendservice:
    container_name: SerwisContainer
    build:
      context: .
      dockerfile: TestBackendService/Dockerfile
    image: testbackendservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DISABLE_HTTPS_REDIRECT=0
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/TestBackendService.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASSWORD}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro

